[package]
name = "factory-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
gstd.workspace = true
pair-client = { path = "../../pair/client" }
